[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.yandex.ru https://*.maps.yandex.net https://api-maps.yandex.ru https://yastatic.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://*.maps.yandex.net https://api-maps.yandex.ru https://*.yandex.ru https://yastatic.net; connect-src 'self' https://*.maps.yandex.net https://api-maps.yandex.ru https://*.yandex.ru https://yastatic.net;"

[build]
  command = "npm run build"
  publish = "build"
  base = "/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 